[package]
name = "rust"
version = "0.1.0"
authors = ["RegisM <regism@tornad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
